"""Golden-set harness.

Runs every manifest clip through the Slice 2 pipeline and writes a status report.
While no real, coach-labeled film exists this runs in fixture mode: poses are
synthetic and nothing here measures accuracy against a coach.

    python -m services.golden_set.harness          # print only
    python -m services.golden_set.harness --write  # also rewrite docs/validation/slice2_report.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from services.cv_worker.pipeline_v2 import run_pose_assessment

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "data/golden_set/manifest.json"
REPORT = ROOT / "docs/validation/slice2_report.md"
HONESTY_LINE = "Do not treat this as athlete validation."


def real_mp4_present(manifest: dict[str, Any], root: Path = MANIFEST.parent) -> bool:
    for clip in manifest.get("clips", []):
        for key in ("camera_side", "camera_45"):
            cam = clip.get(key) or {}
            if cam.get("present") and (root / cam.get("path", "")).is_file():
                return True
    return False


def build_report(manifest_path: Path = MANIFEST) -> str:
    manifest = json.loads(manifest_path.read_text())
    real = real_mp4_present(manifest, manifest_path.parent)
    lines = [
        "# Slice 2 validation report",
        "",
        "Generated by `python -m services.golden_set.harness --write`. Do not edit by hand.",
        "",
        f"golden_set: {manifest.get('golden_set')}",
        f"real_mp4_present: {str(real).lower()}",
        "mode: fixture (synthetic poses, not athlete film)",
        "",
        HONESTY_LINE,
        "No athlete-film MAE is published. No coach labels exist yet, so there is nothing to compare against.",
        "",
    ]
    for clip in manifest["clips"]:
        movement = "release" if clip["movement"] == "release" else "break"
        out = run_pose_assessment(movement=movement, clip_id=clip["clip_id"], height_cm=clip.get("athlete_height_cm"))
        lines.append(
            f"- {clip['clip_id']}: status={out['assessment_status']} cues={len(out['cues'])} "
            f"pose_model={out['versions']['pose_model_version']} source=fixture"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true", help="rewrite docs/validation/slice2_report.md")
    parser.add_argument("--out", type=Path, default=REPORT)
    args = parser.parse_args(argv)
    text = build_report()
    print(text, end="")
    if args.write:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
