"""Golden-set harness.

Runs every manifest clip through the Slice 2 pipeline and writes a status report.
While no real, coach-labeled film exists this runs in fixture mode: poses are
synthetic and nothing here measures accuracy against a coach.

    python -m services.golden_set.harness          # print only
    python -m services.golden_set.harness --write  # rewrite the report only if golden_set is ready and real film is on disk
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from services.api.gates import has_film
from services.cv_worker.pipeline_v2 import run_pose_assessment

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "data/golden_set/manifest.json"
REPORT = ROOT / "docs/validation/slice2_report.md"
HONESTY_LINE = "Do not treat this as athlete validation."


def real_mp4_present(manifest: dict[str, Any], root: Path = MANIFEST.parent) -> bool:
    return any(has_film(clip, root) for clip in manifest.get("clips", []))


def build_report(manifest_path: Path = MANIFEST) -> str:
    manifest = json.loads(manifest_path.read_text())
    real = real_mp4_present(manifest, manifest_path.parent)
    runs = []
    for clip in manifest["clips"]:
        movement = "release" if clip["movement"] == "release" else "break"
        runs.append((clip, run_pose_assessment(movement=movement, clip_id=clip["clip_id"], height_cm=clip.get("athlete_height_cm"))))
    sources = {out["pose_source"] for _, out in runs}
    lines = [
        "# Slice 2 validation report",
        "",
        "Generated by `python -m services.golden_set.harness --write`. Do not edit by hand.",
        "",
        f"golden_set: {manifest.get('golden_set')}",
        f"real_mp4_present: {str(real).lower()}",
        f"mode: {'fixture (synthetic poses, not athlete film)' if sources <= {'fixture'} else ', '.join(sorted(sources))}",
        "",
        HONESTY_LINE,
        "No athlete-film MAE is published. No coach labels exist yet, so there is nothing to compare against.",
        "",
    ]
    for clip, out in runs:
        lines.append(
            f"- {clip['clip_id']}: status={out['assessment_status']} cues={len(out['cues'])} "
            f"pose_model={out['versions']['pose_model_version']} source={out['pose_source']}"
        )
    return "\n".join(lines) + "\n"


def write_blocked(manifest: dict[str, Any], root: Path = MANIFEST.parent) -> str | None:
    """Return a refusal reason, or None when --write may stamp the report."""
    if manifest.get("golden_set") != "ready":
        return "golden_set is not ready"
    if not real_mp4_present(manifest, root):
        return "no real film on disk"
    return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true", help="rewrite docs/validation/slice2_report.md")
    parser.add_argument("--out", type=Path, default=REPORT)
    args = parser.parse_args(argv)
    manifest = json.loads(MANIFEST.read_text())
    text = build_report()
    print(text, end="")
    if args.write:
        reason = write_blocked(manifest)
        if reason:
            print(f"refusing --write: {reason}", file=sys.stderr)
            return 2
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
